version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "bun"
    directory: "/server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "bun"
    directory: "/server/web"
    schedule:
      interval: "weekly"
  - package-ecosystem: "bun"
    directory: "/plugin"
    schedule:
      interval: "weekly"
